# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/userSignIn/test2account
Content-Type: application/json

{
  "password": "test2password"
}
//{
//  "account": "test2account",
//  "password": "test2"
//}

###
POST http://localhost:8080/userAdd
Content-Type: application/json

{
  "account": "test2account",
  "password": "test2password",
  "name": "test2name",
  "email": "test2email",
  "phone": "test2phone"
}

###
PUT http://localhost:8080/userUpdate/2
Content-Type: application/json

{
  "password": "weq",
  "name": "fuck2name",
  "email": "fyck2email",
  "phone": "tasf2phone"
}

###

DELETE http://localhost:8080/userDelete/2
Accept: application/json

###

GET http://localhost:8080/postGet/2
Accept: application/json

###
GET http://localhost:8080/postGetByUser/1
Accept: application/json

###
GET http://localhost:8080/postList
Accept: application/json

###

POST http://localhost:8080/postUpdate/1
Content-Type: application/json

{
  "title" : "수정함",
  "content" : "수정함"
}

###